# Generated by Django 2.0.7 on 2021-04-20 09:17

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210330_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Categorie'),
        ),
    ]
