# Generated by Django 2.0.7 on 2021-05-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_reviewmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmessage',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewmessage',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
