# Generated by Django 2.0.7 on 2021-08-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_categorylang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlang',
            name='description',
            field=models.TextField(),
        ),
    ]
