# Generated by Django 2.0.7 on 2021-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='sub_title',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
