# Generated by Django 2.0.7 on 2021-04-15 20:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_setting_sub_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='setting',
            name='customerservice',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='policies_and_terms',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=True),
            preserve_default=False,
        ),
    ]
