# Generated by Django 2.0.7 on 2021-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210418_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
