# Generated by Django 2.0.7 on 2021-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
