# Generated by Django 2.0.7 on 2021-08-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210810_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
