# Generated by Django 2.0.7 on 2021-08-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userfavourites_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavourites',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
