# Generated by Django 2.0.7 on 2021-08-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210819_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavourites',
            name='price',
        ),
    ]
